services:
  frontend:
    build:
      context: ../..
      dockerfile: dockers/frontend/Dockerfile
    container_name: frontend
    restart: always
    networks:
      - proxy-tier
    environment:
      - VIRTUAL_HOST=$DOMAIN
      - LETSENCRYPT_HOST=$DOMAIN
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - VIRTUAL_PATH=/

networks:
  proxy-tier:
    external: true